### ISSUE TITLE
Composer Support

### ISSUE THREAD

**Issue by nusserstudios** [Daronspence/acf-widgets#19]
Would you be willing to add composer support this project? It would be awesome if you did.

**Comment by daronspence** [comment]
Hey @nusserstudios, what exactly would be needed to support this with composer? As I understand it, I would need to add my plugin to Packagist which is for FOSS projects?

ACF Widgets is not free software (well, it isn't supposed to be). The github repo is simply here for people who want to help by submitting issues or pull requests if they find a bug.

I'm still pretty new to development outside of WordPress so I welcome any help you can offer :)

**Comment by nusserstudios** [comment]
I have a premium license. I will help you out and give you a composer.json file. Elliot Condon has started doing this with ACF Pro. Looks something like this:

{
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "advanced-custom-fields/advanced-custom-fields-pro",
        "version": "5.3.2.2",
        "type": "wordpress-plugin",
        "dist": {
          "type": "zip",
          "url": "http://connect.advancedcustomfields.com/index.php?p=pro&a=download&k=yourkeyhere"
        }
      }
    }
  ]
}

**Comment by nusserstudios** [comment]
I use composer to install plugins in my WordPress installs. I use Sage/Bedrock/Trellis, and Bedrock creates a separate directory so you can't just upload plugins like you do traditionally. Right now I have your premium 1.6 files on a Private Repo.

**Comment by daronspence** [comment]
Gotcha. Hmm, well if you want to submit a pull request, I'd be happy to merge it, I just need to check on EDD's ability to download on demand. I'm sure there's a way to do it, but I vaguely remember something about temporary URLs, even for the Software Licensing Add-on; it might take me a few days to find some time to test it.

Thanks for supporting the plugin btw :)

**Comment by nusserstudios** [comment]
That would be awesome. I will fork it and put in a pull request within the next few days. You may just have to setup a blind URL kind of like the url in ACF Pro. Thank you for working with me Daron, I really appreciate it, and you're welcome as well.

**Comment by nusserstudios** [comment]
You can close this. I set up private repos on bitbucket. Thanks Daron.

**Comment by tyrann0us** [comment]
Hi @Daronspence,
any news regarding the missing `composer.json` file? For developers who bought this plugin and want to use e. g. [Bedrock](https://roots.io/bedrock/) (as @nusserstudios explained) this would definitely help alot.
Thanks!

**Comment by nusserstudios** [comment]
I just put them in a private git Repo tyrann0us. Just use the Roots Soil composer file and update it with this plugins info. https://github.com/roots/soil/blob/master/composer.json

**Comment by tyrann0us** [comment]
Thanks for the suggestion.
Doing this I would have to manually update the repository everytime this plugin gets updated. Not very useful when all you need for a good workflow is a simple `composer.json` in this repository.
And @Daronspence, there'd be no need to add this plugin to Packagist.

**Comment by nusserstudios** [comment]
BTW, you wouldnt need to authenticate it with a s/n @Daronspence. Just the composer file would work in the Premium, and we can update the version with composer.

**Comment by daronspence** [comment]
If someone wants to make a PR, I'll merge it. I assume I'll need to update the file Everytime I tag a new release?

**Comment by nusserstudios** [comment]
Just to be sure, are we talking the Premium plugin? @Daronspence @tyrann0us, if so, you don't want everyone to have access, and it would have to be included with the premium plugin, and you'd have to put it up on a blind url and make sure bots cannot crawl it.

**Comment by tyrann0us** [comment]
@Daronspence see #24.
Yes, you'd need to update the `version` property which each release.

**Comment by tyrann0us** [comment]
@Daronspence any news on this?

**Comment by daronspence** [comment]
Merged!

**Comment by tyrann0us** [comment]
So this issue can be closed, @nusserstudios,
Thanks @Daronspence!
