### ISSUE TITLE
Clone field support

### ISSUE THREAD

**Issue by tyrann0us** [Daronspence/acf-widgets#25]
I created a field in a field group for pages and and a second field in a field group for a widget. The second field is a clone of the first one.
When I save the widget on the widgets page (wp-admin/widgets.php), the cloned field won't be saved. Can you confirm this?

Edit: I needed to check "Prefix Field Names" to made it work.

**Comment by daronspence** [comment]
So is this fixed then @tyrann0us ? I haven't spent too much time with the clone field, so I'm not sure why it wouldn't work. ACF Core is responsible for the saving of those values in the admin area.

**Comment by tyrann0us** [comment]
Well prefixing the field seems to work but I encountered something else:
Sometimes clone fields won't show up in the widget. This isn't something reproducible so I can't describe the steps to see this happening. The fact is it happened twice to me while configuring fields.

**Comment by daronspence** [comment]
In re: to your field not rendering, I feel that might be some sort of cache thing. Especially if it's difficult to reproduce. I know ACF does some internal caching but I'm not sure how prevalent it is.

The clone field documentation may provide some insights into why the the field wasn't saved. Likely a naming conflict (which it seems like you discovered). https://www.advancedcustomfields.com/resources/clone/
